### ISSUE TITLE
instructions on how to deploy

### ISSUE THREAD

**Issue by Bad3r** [MedzikUser/wrangler-cdn#268]
Hi there! 👋
are there any instructions on how to set up this proxy for Imgur?

**Comment by OskarKarpinski** [comment]
1. Fork this repository
2. You must change [this line](https://github.com/MedzikUser/wrangler-cdn/blob/main/wrangler.toml#L4) to your account id from cloudflare.
3. Create `CF_API_TOKEN` enviromanet variable on github repository with your cloudflare api token

![image](https://user-images.githubusercontent.com/87065584/212548978-e2eaa6d0-5fc3-42ae-b0da-82678da971f6.png)

4. Finally, you must allow runs github actions on your repository and manually run `Deplay` workflow.

Sorry for the lack of documentation.

**Comment by Bad3r** [comment]
No worries thank you! I'll try it out and report back if I have any issues.
This could be the start of the documentation :D
